[theme]
base = "dark"
primaryColor = "#FF5733"
backgroundColor = "#121212"
secondaryBackgroundColor = "#232323"
textColor = "#EAEAEA"
font = "monospace"

[server]
headless = true
enableCORS = false
port = 8501
allowedOrigins = ["http://localhost", "https://tu-dominio.com"]

[cache]
enable = true
ttl = 3600

[script]
autoRerun = true

[logger]
level = "debug"
