[theme]
primaryColor="#33ffd0"
backgroundColor="#121212"
secondaryBackgroundColor="#0f0b1a"
textColor="#e6aa1d"
font="monospace"


[server]
headless = true
enableCORS = false
port = 8501
allowedOrigins = ["http://localhost", "https://tu-dominio.com"]

[cache]
enable = true
ttl = 3600

[script]
autoRerun = true

[logger]
level = "debug"
